AWSTemplateFormatVersion: 2010-09-09
Description: "Creates infrastructure for Thumnbail Creator"

Parameters:
  RawBucketName:
    Type: String
    Default: rawimages
    Description: Enter the name of the Raw Images Bucket

  ThumbnailBucketName:
    Type: String
    Default: thumbnailimages
    Description: Enter the name of the Thumbnail Images Bucket

  ApiGatewayName:
    Type: String
    Default: tcapigateway
    Description: Enter the name of the API Gateway

Resources:
  AppRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "tc-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:*"
                Resource: "*"
      RoleName: tc-role

  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RawBucketName

  ThumbnailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ThumbnailBucketName

  ApiGatewayRest:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref ApiGatewayName
      BinaryMediaTypes:
        - image/png
      EndpointConfiguration:
        Types:
          - REGIONAL
    DependsOn:
      - RawBucket

  BucketApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      PathPart: !Ref RawBucketName
      RestApiId: !Ref ApiGatewayRest
      ParentId: !GetAtt
        - ApiGatewayRest
        - RootResourceId
    DependsOn:
      - ApiGatewayRest

  BucketItemApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      PathPart: "{item}"
      RestApiId: !Ref ApiGatewayRest
      ParentId: !Ref BucketApiResource
    DependsOn:
      - ApiGatewayRest
      - BucketApiResource

  BucketItemApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRest
      ResourceId: !Ref BucketItemApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS
        Credentials: !GetAtt
          - AppRole
          - Arn
        IntegrationHttpMethod: PUT
        Uri:
          Fn::Join:
            - ""
            - - "arn:aws:apigateway:us-east-1:s3:path/"
              - !Ref RawBucketName
              - "{item}"
