AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Resize Trigger

Globals:
    Function:
        Timeout: 10

Resources:
  CreateThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateThumbnail
      CodeUri: src/CreateThumbnailFunction/bin/Debug/netcoreapp2.1/publish
      Handler: CreateThumbnailFunction::CreateThumbnailFunctions.CreateThumbnailFunction::Execute
      Runtime: dotnetcore2.1
      Events:
        ResizeImageEvent:
          Type: S3
          Properties:
            Bucket: example-bucket
            Events: s3.ObjectCreated:*